var chdata={
labels: [],
datasets: [
{label: 'Fälle',
type: 'bar',
backgroundColor: window.chartColors.blue,
data: []},
{label: '7-Tg. Inzidenz',
type: 'line',
pointBackgroundColor: 'orange',
borderColor: 'orange',
data: []},
{label: 'Hospitalisierung',
type: 'bar',
backgroundColor: window.chartColors.red,
data: []},
{label: 'Hosp. (∑ 14-Tg.)',
type: 'line',
hidden: true,
borderColor: 'rgba(0,255,0,0.5)',
borderWidth: 1.5,
pointRadius: 0,
data: []},
{label: 'Aktuell im Krankenhaus',
type: 'line',
pointBackgroundColor: 'green',
borderColor: 'green',
data: []},
{label: 'Todesfälle',
type: 'bar',
backgroundColor: 'black',
data: []},
]};

