var chdata={
labels: [],
datasets: [
{label: 'Fälle',
type: 'bar',
backgroundColor: window.chartColors.blue,
yAxisID: 'first-y-axis',
data: []},
{label: '7-Tg. Inzidenz',
type: 'line',
fill: false,
pointBackgroundColor: 'orange',
borderColor: 'orange',
yAxisID: 'first-y-axis',
data: []},
{label: 'Hospitalisierung',
type: 'bar',
backgroundColor: window.chartColors.red,
yAxisID: 'first-y-axis',
data: []},
{label: 'Hospitalisierung (∑ 14-Tg.)',
type: 'line',
pointRadius: 0,
fill: false,
borderColor: 'rgba(0,128,0,0.5)',
borderWidth: 2,
yAxisID: 'first-y-axis',
data: []},
{label: 'Todesfälle',
type: 'bar',
backgroundColor: 'black',
yAxisID: 'first-y-axis',
data: []},
{label: 'Todesfälle je Woche',
type: 'line',
fill: false,
spanGaps: true,
borderColor: 'rgba(128,128,128,1)',
borderWidth: 2,
pointRadius: 2,
yAxisID: 'first-y-axis',
data: []},
]};

